CREATE TABLE USERS(
FIRST_NAME VARCHAR(30),
SURNAME VARCHAR(30),
LOGIN VARCHAR(30),
PASSWORD VARCHAR(40));
INSERT INTO USERS (LOGIN, PASSWORD, FIRST_NAME, SURNAME) VALUES ('uz1', 'pass1', 'Monika', 'H');
INSERT INTO USERS (LOGIN, PASSWORD, FIRST_NAME, SURNAME) VALUES ('uz2', 'pass2', 'Magda', 'W');
